/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Modelo.Entrada;
import controlador.Registro;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.TimeZone;
import javax.swing.JOptionPane;

/**
 *
 * @author Pía Trujillo / José Ignacio Gutiérrez
 */
public class Modificar extends javax.swing.JFrame {

    Registro reg = new Registro();    
    
    /**
     * Creates new form Modificar
     */
    public Modificar() {
        initComponents();
        
        this.jtxt_titulo.setEditable(false);
        this.jtxt_dia.setEditable(false);
        this.jtxt_mes.setEditable(false);
        this.jtxt_anio.setEditable(false);
        this.jtxt_precio.setEditable(false);
        this.jtxt_entrada.setEditable(false);
        this.jckb_disponible.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxt_alias = new javax.swing.JTextField();
        jtxt_titulo = new javax.swing.JTextField();
        jtxt_dia = new javax.swing.JTextField();
        jtxt_precio = new javax.swing.JTextField();
        jtxt_entrada = new javax.swing.JTextField();
        jbtn_buscar = new javax.swing.JButton();
        jckb_disponible = new javax.swing.JCheckBox();
        jbtn_actualizar = new javax.swing.JButton();
        jbtn_limpiar = new javax.swing.JButton();
        jbtn_volver = new javax.swing.JButton();
        jbtn_editar = new javax.swing.JButton();
        jtxt_mes = new javax.swing.JTextField();
        jtxt_anio = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar Película");

        jLabel1.setText("Ingrese Alias");

        jLabel2.setText("Título");

        jLabel3.setText("Fecha de Estreno");

        jLabel4.setText("Precio Entrada");

        jLabel5.setText("Entradas Vendidas");

        jLabel6.setText("Disponible");

        jbtn_buscar.setText("Buscar");
        jbtn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_buscarActionPerformed(evt);
            }
        });

        jbtn_actualizar.setText("Actualizar");
        jbtn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_actualizarActionPerformed(evt);
            }
        });

        jbtn_limpiar.setText("Limpiar");
        jbtn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_limpiarActionPerformed(evt);
            }
        });

        jbtn_volver.setText("Volver");
        jbtn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_volverActionPerformed(evt);
            }
        });

        jbtn_editar.setText("Editar");
        jbtn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_editarActionPerformed(evt);
            }
        });

        jtxt_mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_mesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jckb_disponible)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtxt_alias, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtn_buscar))
                    .addComponent(jtxt_titulo)
                    .addComponent(jtxt_precio)
                    .addComponent(jtxt_entrada)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtxt_dia, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxt_mes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxt_anio)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jbtn_editar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtn_actualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtn_limpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtn_volver)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxt_alias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_buscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxt_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxt_dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt_mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt_anio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxt_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jckb_disponible))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_actualizar)
                    .addComponent(jbtn_limpiar)
                    .addComponent(jbtn_volver)
                    .addComponent(jbtn_editar))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_volverActionPerformed
        
        dispose();
        
    }//GEN-LAST:event_jbtn_volverActionPerformed

    private void jbtn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_buscarActionPerformed
        
        String alias = this.jtxt_alias.getText();
        
        Entrada entrada = reg.buscarPorAlias(alias);
        
        String titulo = entrada.getTitulo();
        int precio = entrada.getPrecio();
        Date fecha = entrada.getFuncion();
        int cantidadEntrada = entrada.getCantidadEntrada();
        boolean disponible = entrada.isDisponible();
        
        this.jtxt_titulo.setText(titulo);
        
        SimpleDateFormat getYearFormat = new SimpleDateFormat("yyyy");
        String anio = getYearFormat.format(fecha);
        this.jtxt_anio.setText(anio);

        SimpleDateFormat getMonthFormat = new SimpleDateFormat("MM");
        String mes = getMonthFormat.format(fecha);
        this.jtxt_mes.setText(mes);
        
        SimpleDateFormat getDayFormat = new SimpleDateFormat("dd");
        String dia = getDayFormat.format(fecha);
        this.jtxt_dia.setText(dia);
        
        this.jtxt_precio.setText(String.valueOf(precio));
        this.jtxt_entrada.setText(String.valueOf(cantidadEntrada));
        this.jckb_disponible.setSelected(disponible);
    }//GEN-LAST:event_jbtn_buscarActionPerformed

    private void jbtn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_editarActionPerformed
        
        this.jtxt_titulo.setEditable(true);
        this.jtxt_dia.setEditable(true);
        this.jtxt_mes.setEditable(true);
        this.jtxt_anio.setEditable(true);
        this.jtxt_precio.setEditable(true);
        this.jckb_disponible.setEnabled(true);
        this.jtxt_titulo.requestFocus();
    }//GEN-LAST:event_jbtn_editarActionPerformed

    private void jbtn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_actualizarActionPerformed
        
        String titulo, alias, dia, mes, anio, fechaStr;
        Date fecha;
        int precio, cantidadEntrada;
        boolean disponible;
        
        titulo = this.jtxt_titulo.getText();
        if (titulo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese Título", "Valicación", 2);
            this.jtxt_titulo.requestFocus();
            return;
        }
        
        alias = this.jtxt_alias.getText();
        if (alias.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese Alias", "Valicación", 2);
            this.jtxt_alias.requestFocus();
            return;
        }
        
        dia = this.jtxt_dia.getText();
        mes = this.jtxt_mes.getText();
        anio = this.jtxt_anio.getText();
        
        if (dia.isEmpty() || mes.isEmpty() || anio.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese Fecha", "Valicación", 2);
            this.jtxt_dia.requestFocus();
            return;
        }
        
        fechaStr = dia + "/" + mes + "/" + anio;
        SimpleDateFormat formateo = new SimpleDateFormat("dd/MM/yyyy");
        
        try {
            fecha = formateo.parse(fechaStr);
        } 
        catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Ingrese formato de fecha DD/MM/AAAA", "Validación", 2);
            this.jtxt_dia.requestFocus();
            return;
        }
        
        try {
            precio = Integer.parseInt(this.jtxt_precio.getText());            
        } 
        catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese un valor numérico", "Validación", 2);
            this.jtxt_precio.requestFocus();
            return;
        }
        
        disponible = this.jckb_disponible.isSelected();
        
        cantidadEntrada = Integer.parseInt(this.jtxt_entrada.getText());
        
        Entrada entrada = new Entrada(titulo, alias, fecha, cantidadEntrada, precio, disponible);
                
        reg.actualizar(entrada);
        
        JOptionPane.showMessageDialog(this, "Datos Actualizados", "Confirmación", 1); 
        
//        int precio, entradas, dia, mes, anio;
//        String titulo, alias;
//        boolean disponible;
//        Date fecha = null;
//        
//        
//        alias = this.jtxt_alias.getText();
//        titulo = this.jtxt_titulo.getText();
//        //DIA
//        //MES
//        //AÑO
//        precio = Integer.parseInt(this.jtxt_precio.getText());
//        entradas = Integer.parseInt(this.jtxt_entrada.getText());
//        disponible = this.jckb_disponible.isSelected();
//        
//        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
//        
//        
//        
//        try {
//            fecha = formato.parse(this.jtxt_dia.getText());
//        } 
//        catch (ParseException e) {
//            System.out.println("Error de actualización de fecha" + e.getMessage());
//        }
//        
//        Entrada entrada = new Entrada(titulo, alias, fecha, entradas, precio, disponible);
//        
//        reg.actualizar(entrada);
//        JOptionPane.showMessageDialog(this, "Datos Actualizados", "Confirmación", 1);    
        
    }//GEN-LAST:event_jbtn_actualizarActionPerformed

    private void jbtn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_limpiarActionPerformed
        
        this.jtxt_titulo.setText("");
        this.jtxt_alias.setText("");
        this.jtxt_dia.setText("");
        this.jtxt_entrada.setText("");
        this.jtxt_precio.setText("");
        this.jckb_disponible.setSelected(false);
    }//GEN-LAST:event_jbtn_limpiarActionPerformed

    private void jtxt_mesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_mesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_mesActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Modificar().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jbtn_actualizar;
    private javax.swing.JButton jbtn_buscar;
    private javax.swing.JButton jbtn_editar;
    private javax.swing.JButton jbtn_limpiar;
    private javax.swing.JButton jbtn_volver;
    private javax.swing.JCheckBox jckb_disponible;
    private javax.swing.JTextField jtxt_alias;
    private javax.swing.JTextField jtxt_anio;
    private javax.swing.JTextField jtxt_dia;
    private javax.swing.JTextField jtxt_entrada;
    private javax.swing.JTextField jtxt_mes;
    private javax.swing.JTextField jtxt_precio;
    private javax.swing.JTextField jtxt_titulo;
    // End of variables declaration//GEN-END:variables
}
